name: Feature request
description: Suggest an idea to improve this library
title: "[FEATURE] <title>"
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    label: Are you using the latest version of this library?
    description: Please confirm that you are using the latest version of next-safe-action.
    options:
    - label: I verified that the issue exists in the latest next-safe-action release
      required: true
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Suggest an idea
    description: Is your feature request related to a problem? Do you have a suggestion for improving this library? Please describe it here.
    placeholder: I'd like to see ... implemented because...
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the feature request here.
  validations:
    required: false